-- ============================================================
-- Presencer — notifiche granulari per modifiche nello spazio
-- Esegui una volta in Supabase → SQL Editor → New query → Run
-- ============================================================

create table if not exists notification_preferences (
  profile_id uuid primary key references profiles(id) on delete cascade,
  enabled boolean not null default false,
  attendance boolean not null default true,
  recurring boolean not null default true,
  schedule boolean not null default true,
  calendar boolean not null default true,
  lesson_log boolean not null default true,
  members boolean not null default true,
  updated_at timestamptz not null default now()
);

create table if not exists app_events (
  id bigint generated by default as identity primary key,
  workspace_id uuid not null references workspaces(id) on delete cascade,
  actor_profile_id uuid references profiles(id) on delete set null,
  category text not null check (category in (
    'attendance','recurring','schedule','calendar','lesson_log','members'
  )),
  action text not null check (action in ('insert','update','delete')),
  title text not null,
  body text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_app_events_workspace_id
  on app_events (workspace_id, id desc);

alter table notification_preferences enable row level security;
alter table app_events enable row level security;

drop policy if exists np_select_self on notification_preferences;
create policy np_select_self on notification_preferences for select
  using (is_my_profile(profile_id));

drop policy if exists np_insert_self on notification_preferences;
create policy np_insert_self on notification_preferences for insert
  with check (is_my_profile(profile_id));

drop policy if exists np_update_self on notification_preferences;
create policy np_update_self on notification_preferences for update
  using (is_my_profile(profile_id))
  with check (is_my_profile(profile_id));

drop policy if exists events_select_member on app_events;
create policy events_select_member on app_events for select
  using (is_member(workspace_id));

grant select, insert, update on notification_preferences to authenticated;
grant select on app_events to authenticated;

create or replace function record_presencer_event()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  row_data record;
  ws_id uuid;
  actor_id uuid;
  actor_name text;
  target_name text;
  calendar_name text;
  event_category text := tg_argv[0];
  event_title text;
  event_body text;
  weekday_names text[] := array['Lunedì','Martedì','Mercoledì','Giovedì','Venerdì','Sabato','Domenica'];
begin
  if tg_op = 'DELETE' then row_data := old; else row_data := new; end if;

  -- Non moltiplicare gli avvisi generati dalle cancellazioni a cascata.
  if pg_trigger_depth() > 1 then
    if tg_op = 'DELETE' then return old; else return new; end if;
  end if;

  if tg_table_name = 'profiles' and tg_op = 'UPDATE'
     and new.name is not distinct from old.name
     and new.role is not distinct from old.role then
    return new;
  end if;

  case tg_table_name
    when 'attendance' then
      if row_data.slot_id is not null then
        select c.workspace_id into ws_id
          from slots s join calendars c on c.id = s.calendar_id
          where s.id = row_data.slot_id;
      else
        select c.workspace_id into ws_id
          from extra_slots e join calendars c on c.id = e.calendar_id
          where e.id = row_data.extra_slot_id;
      end if;
      if row_data.instructor_id is not null then
        select name into target_name from profiles where id = row_data.instructor_id;
      end if;
      target_name := coalesce(target_name, row_data.guest_name, 'Qualcuno');
      event_title := case tg_op
        when 'INSERT' then 'Presenza registrata'
        when 'UPDATE' then 'Presenza aggiornata'
        else 'Presenza rimossa' end;
      event_body := case tg_op
        when 'DELETE' then target_name || ' · ' || to_char(row_data.date, 'DD/MM/YYYY')
        else target_name || ': ' || initcap(row_data.status) || ' · ' || to_char(row_data.date, 'DD/MM/YYYY') end;

    when 'recurring_presence' then
      select c.workspace_id into ws_id
        from slots s join calendars c on c.id = s.calendar_id
        where s.id = row_data.slot_id;
      select name into target_name from profiles where id = row_data.instructor_id;
      event_title := case tg_op when 'DELETE' then 'Ricorrenza disattivata' else 'Ricorrenza attivata' end;
      event_body := coalesce(target_name, 'Un membro') || case tg_op
        when 'DELETE' then ' ha disattivato una presenza ricorrente.'
        else ' risulta ' || lower(row_data.status) || ' ogni settimana.' end;

    when 'lesson_logs' then
      if row_data.slot_id is not null then
        select c.workspace_id into ws_id
          from slots s join calendars c on c.id = s.calendar_id
          where s.id = row_data.slot_id;
      else
        select c.workspace_id into ws_id
          from extra_slots e join calendars c on c.id = e.calendar_id
          where e.id = row_data.extra_slot_id;
      end if;
      select name into target_name from profiles where id = row_data.instructor_id;
      event_title := case tg_op
        when 'INSERT' then 'Registro lezione aggiunto'
        when 'UPDATE' then 'Registro lezione aggiornato'
        else 'Registro lezione eliminato' end;
      event_body := coalesce(target_name, 'Un membro') || ' · ' || to_char(row_data.date, 'DD/MM/YYYY');

    when 'extra_slots' then
      select workspace_id into ws_id from calendars where id = row_data.calendar_id;
      event_title := case tg_op
        when 'INSERT' then 'Lezione extra aggiunta'
        when 'UPDATE' then 'Lezione extra modificata'
        else 'Lezione extra eliminata' end;
      event_body := row_data.label || ' · ' || to_char(row_data.date, 'DD/MM/YYYY') ||
        ' ' || to_char(row_data.start_time, 'HH24:MI');

    when 'slots' then
      select workspace_id into ws_id from calendars where id = row_data.calendar_id;
      event_title := case tg_op
        when 'INSERT' then 'Orario aggiunto'
        when 'UPDATE' then 'Orario modificato'
        else 'Orario eliminato' end;
      event_body := weekday_names[row_data.weekday + 1] || ' · ' || row_data.label ||
        ' ' || to_char(row_data.start_time, 'HH24:MI');

    when 'calendars' then
      ws_id := row_data.workspace_id;
      event_title := case tg_op
        when 'INSERT' then 'Calendario creato'
        when 'UPDATE' then 'Calendario modificato'
        else 'Calendario eliminato' end;
      event_body := row_data.name;

    when 'calendar_periods' then
      ws_id := row_data.workspace_id;
      select name into calendar_name from calendars where id = row_data.calendar_id;
      event_title := case tg_op
        when 'INSERT' then 'Cambio calendario programmato'
        when 'UPDATE' then 'Cambio calendario modificato'
        else 'Cambio calendario annullato' end;
      event_body := coalesce(calendar_name, 'Calendario') || ' · dal ' || to_char(row_data.start_date, 'DD/MM/YYYY');

    when 'profiles' then
      ws_id := row_data.workspace_id;
      event_title := case tg_op
        when 'INSERT' then 'Nuovo membro'
        when 'UPDATE' then 'Membro aggiornato'
        else 'Membro rimosso' end;
      event_body := row_data.name || case
        when tg_op = 'UPDATE' then ' · ruolo: ' || case row_data.role when 'admin' then 'amministratore' else 'istruttore' end
        else '' end;
  end case;

  if ws_id is null then
    if tg_op = 'DELETE' then return old; else return new; end if;
  end if;

  select id, name into actor_id, actor_name
    from profiles
    where workspace_id = ws_id and user_id = auth.uid()
    limit 1;

  insert into app_events (
    workspace_id, actor_profile_id, category, action, title, body, metadata
  ) values (
    ws_id, actor_id, event_category, lower(tg_op), event_title, event_body,
    jsonb_build_object(
      'table', tg_table_name,
      'record_id', row_data.id,
      'actor_name', actor_name
    )
  );

  if tg_op = 'DELETE' then return old; else return new; end if;
end;
$$;

drop trigger if exists notify_attendance_changes on attendance;
create trigger notify_attendance_changes after insert or update or delete on attendance
  for each row execute function record_presencer_event('attendance');

drop trigger if exists notify_recurring_changes on recurring_presence;
create trigger notify_recurring_changes after insert or update or delete on recurring_presence
  for each row execute function record_presencer_event('recurring');

drop trigger if exists notify_lesson_log_changes on lesson_logs;
create trigger notify_lesson_log_changes after insert or update or delete on lesson_logs
  for each row execute function record_presencer_event('lesson_log');

drop trigger if exists notify_extra_slot_changes on extra_slots;
create trigger notify_extra_slot_changes after insert or update or delete on extra_slots
  for each row execute function record_presencer_event('schedule');

drop trigger if exists notify_slot_changes on slots;
create trigger notify_slot_changes after insert or update or delete on slots
  for each row execute function record_presencer_event('schedule');

drop trigger if exists notify_calendar_changes on calendars;
create trigger notify_calendar_changes after insert or update or delete on calendars
  for each row execute function record_presencer_event('calendar');

drop trigger if exists notify_calendar_period_changes on calendar_periods;
create trigger notify_calendar_period_changes after insert or update or delete on calendar_periods
  for each row execute function record_presencer_event('calendar');

drop trigger if exists notify_profile_changes on profiles;
create trigger notify_profile_changes after insert or update or delete on profiles
  for each row execute function record_presencer_event('members');

-- Supabase Realtime deve pubblicare la tabella che alimenta i client connessi.
do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime')
     and not exists (
       select 1 from pg_publication_tables
       where pubname = 'supabase_realtime'
         and schemaname = 'public'
         and tablename = 'app_events'
     ) then
    alter publication supabase_realtime add table app_events;
  end if;
end $$;

